<?php
namespace Phossa\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-01 at 06:56:37.
 */
class QueryBuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QueryBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryBuilder([
            //'dialectClass'  => '\Phossa\Query\Dialect\Common',
            //'autoQuote'     => false,
        ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phossa\Query\QueryBuilder::setQueryMode
     */
    public function testSetQueryMode()
    {
        var_dump(
            $this->object
                 ->select()
                 ->distinct()
                 ->field('wow', 'w')
                 ->field('yoy')
                 ->from('bingo', 'b')
                 ->from('xxx')
                 ->getStatement()
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::getQueryMode
     * @todo   Implement testGetQueryMode().
     */
    public function testGetQueryMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::isStrictMode
     * @todo   Implement testIsStrictMode().
     */
    public function testIsStrictMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::setDialect
     * @todo   Implement testSetDialect().
     */
    public function testSetDialect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::getDialect
     * @todo   Implement testGetDialect().
     */
    public function testGetDialect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::setTablePrefix
     * @todo   Implement testSetTablePrefix().
     */
    public function testSetTablePrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::getTablePrefix
     * @todo   Implement testGetTablePrefix().
     */
    public function testGetTablePrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::warning
     * @todo   Implement testWarning().
     */
    public function testWarning()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::getStatement
     * @todo   Implement testGetStatement().
     */
    public function testGetStatement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::getBindings
     * @todo   Implement testGetBindings().
     */
    public function testGetBindings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phossa\Query\QueryBuilder::setLogger
     * @todo   Implement testSetLogger().
     */
    public function testSetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
